### ISSUE TITLE
saveSession is asynchronous function?

### ISSUE THREAD

**Issue by DreamMoon93** [longztian/koa-session-minimal#25]
Q: Sometimes there may be some problems with mysql db, resulting in slower storage. Sometimes when saving the session, it may not be successful, and the client will initiate a request to obtain the value of the session. Since saveSession is an asynchronous operation, it is possible to obtain the current session value or the value that has not been updated in history。

Should we add await to saveSession to synchronize the storage session?

**Comment by lzztt** [comment]
I think adding `await` won't solve the problem, as `saveSession()` is the last action for a request. There is no further action after it to benefit from the synchronization.

When the underneath store is slow to commit an update, or having a replication delay if it's distributed, it's possible that the next request reads the previous version of session state from the session store.
