### ISSUE TITLE
cant delete session

### ISSUE THREAD

**Issue by yuu2lee4** [longztian/koa-session-minimal#6]
![image](https://cloud.githubusercontent.com/assets/8046366/21292089/13faa7b4-c533-11e6-8140-b21dd5005515.png)

although i set session to null in a setTimeout, and terminal also show it is null, but when i call getPin int the second, the ctx.session.pin has a value

![image](https://cloud.githubusercontent.com/assets/8046366/21292092/265f2d4e-c533-11e6-878c-13dfee8cfbc0.png)

my enviroment: macos, node 7.2.0, koa-session-minimal-3.0.2, koa-generic-session-mongo-0.3.0

**Comment by yuu2lee4** [comment]
![image](https://cloud.githubusercontent.com/assets/8046366/21292226/46d95d4c-c538-11e6-886d-c733c86b3f24.png)
and i found a strange thing,  i seted session.user, then i console it, the object has no 'sid' and 'ttl' , but after i setted session.pin ,  it has 'sid' and 'ttl'

**Comment by longztian** [comment]
> and i found a strange thing, i seted session.user, then i console it, the object has no 'sid' and 'ttl' , but after i setted session.pin , it has 'sid' and 'ttl'
Hi yuu2lee4,

For the second question, looks like [mongo store modified the session data](https://github.com/pavelvlasov/koa-generic-session-mongo/blob/master/src/store.js#L153) before saving it (in `set(sid, sess, ttl)`).

**Comment by longztian** [comment]
For the first question "cannot delete session", can you move the code out of the `setTimeout()` function?

Koa uses co-routine for async programming. Middlewares synchronize (pause/resume) their execution based on async/await calls (Promises). `setTimeout()` is an async call based on time, lives outside of the co-routine synchronization. So it cannot cooperate with any Koa middlewares, i.e., the session middleware could finish saving the session data to underneath store before the setTimeout call get executed (set `session = null`). It actually doesn't yield the setTimeout call at all.

Let me know if you need more help.

**Comment by yuu2lee4** [comment]
as you see, i want remove session.pin after 2 minutes when getPin was called by browser.i will write a async function called removePin based on setTimeout, and use it like this: replacing setTimeout with removePin in getPin, but not use await in case of blocking setTing ctx.body, if it dont help, the plan B is: after 2 minutes, the browser call the interfac removePin, then the koa remove the session.pin 
 i will let you know if it worked

**Comment by longztian** [comment]
Hi yuu2lee4,

I can think of 3 ways to do this:
1. manipulate session data directly in the database (session store). Do a query on the session collection in MongoDB, find documents that contain "pin" and remove "pin" if the session is older than 2 minutes, keep the rest of the session data.
2. set a TTL for pin. In session, you would have "pin" and "pin_ttl" data. Your application can ignore the "pin" if the "pin_ttl" is expired (older than 2 minutes)
3. set the TTL for sessions that contain "pin" to 2 minutes.

For the 1st solution, it can be handled by a separated script in any language, with a cron job that runs for every 2 minutes.
For the 2nd solution, you need to save "pin_ttl" along with "pin". I use this method for the PIN generation for my website.
For the 3rd solution, you can take advantage of the ["dynamic expiration" feature of koa-session-minimal](https://github.com/longztian/koa-session-minimal#session-expiration), to set the guest session to be expired after 2 minutes.
Here is some code example for the 3rd solution (notice that the `cookie` option is dynamically returned by a function, the `maxAge` is calculated based on the existence of `ctx.session.pin`):
```javascript
session({
  cookie: ctx => ({
    maxAge: ctx.session.pin ? TWO_MINITES : ONE_MONTH,
    store: new MongoStore(),
  })
})
```

Let me know if this works for you.

**Comment by yuu2lee4** [comment]
thanks for your help, the 3rd method works well.
