### ISSUE TITLE
'secure' cookie option

### ISSUE THREAD

**Issue by olsonpm** [longztian/koa-session-minimal#7]
any reason you provided a default for the 'secure' option?  the cookies module dynamic default seems more intuitive than your hardcoding of `false`

**Comment by longztian** [comment]
Thank you, olsonpm.
It is a very good suggestion. I will remove the default value for `secure` option.

**Comment by longztian** [comment]
released v3.0.3

**Comment by olsonpm** [comment]
Wow - thanks so much.

btw, this module was well written and documented.  I had the pleasurable experience of writing code that just worked.
